CREATE TABLE :DB_SCHEMA_NAME.nation
(N_NATIONKEY INTEGER, 
N_NAME CHAR(25), 
N_REGIONKEY INTEGER, 
N_COMMENT VARCHAR(152),
dummy text);
ALTER TABLE :DB_SCHEMA_NAME.nation ADD PRIMARY KEY (n_nationkey);
