CREATE TABLE :DB_SCHEMA_NAME.partsupp
(PS_PARTKEY INT,
PS_SUPPKEY INT,
PS_AVAILQTY INTEGER,
PS_SUPPLYCOST DECIMAL(15,2),
PS_COMMENT VARCHAR(199)
);
ALTER TABLE :DB_SCHEMA_NAME.partsupp ADD PRIMARY KEY (ps_partkey, ps_suppkey);
